# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: #27292F;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.MainLayout = QtWidgets.QHBoxLayout()
        self.MainLayout.setSpacing(0)
        self.MainLayout.setObjectName("MainLayout")
        self.InputLayout = QtWidgets.QVBoxLayout()
        self.InputLayout.setObjectName("InputLayout")
        self.LanguageLayout = QtWidgets.QHBoxLayout()
        self.LanguageLayout.setSpacing(15)
        self.LanguageLayout.setObjectName("LanguageLayout")
        self.SourceComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SourceComboBox.sizePolicy().hasHeightForWidth())
        self.SourceComboBox.setSizePolicy(sizePolicy)
        self.SourceComboBox.setMinimumSize(QtCore.QSize(120, 50))
        self.SourceComboBox.setStyleSheet("QComboBox{\n"
"    border: none;\n"
"    background-color: #27292F;\n"
"    font-family: \'Microsoft Yahei\';\n"
"    font-size: 12pt;\n"
"    color: white;\n"
"    padding-left: 10px;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color: #2F3137;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border-image:url(:/ComboBox/下拉箭头.svg);\n"
"    margin-right: 8px;\n"
"    margin-top: 15px;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    outline: none;\n"
"    color: #cccccc;\n"
"    font: 12pt \"Microsoft Tahei\";\n"
"    background: #303338;\n"
"    padding: 12px 6px 12px 6px;\n"
"}")
        self.SourceComboBox.setFrame(False)
        self.SourceComboBox.setObjectName("SourceComboBox")
        self.SourceComboBox.addItem("")
        self.SourceComboBox.addItem("")
        self.SourceComboBox.addItem("")
        self.SourceComboBox.addItem("")
        self.SourceComboBox.addItem("")
        self.SourceComboBox.addItem("")
        self.SourceComboBox.addItem("")
        self.SourceComboBox.addItem("")
        self.SourceComboBox.addItem("")
        self.SourceComboBox.addItem("")
        self.LanguageLayout.addWidget(self.SourceComboBox)
        self.SwapButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SwapButton.sizePolicy().hasHeightForWidth())
        self.SwapButton.setSizePolicy(sizePolicy)
        self.SwapButton.setMinimumSize(QtCore.QSize(0, 0))
        self.SwapButton.setMaximumSize(QtCore.QSize(1111111, 1111111))
        self.SwapButton.setStyleSheet("QPushButton{\n"
"    width: 40px;\n"
"    height: 30px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    font-size: 30pt;\n"
"    color: #858A98;\n"
"    margin-left: 5px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QToolTip{\n"
"    background-color: #36393E;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    font: 8pt \"Microsoft Yahei\";\n"
"    color: #A7ABBD;\n"
"}")
        self.SwapButton.setObjectName("SwapButton")
        self.LanguageLayout.addWidget(self.SwapButton)
        self.TargetComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TargetComboBox.sizePolicy().hasHeightForWidth())
        self.TargetComboBox.setSizePolicy(sizePolicy)
        self.TargetComboBox.setMinimumSize(QtCore.QSize(120, 50))
        self.TargetComboBox.setStyleSheet("QComboBox{\n"
"    border: none;\n"
"    background-color: #27292F;\n"
"    font-family: \'Microsoft Yahei\';\n"
"    font-size: 12pt;\n"
"    color: white;\n"
"    padding-left: 10px;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    background-color: #2F3137;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border-image:url(:/ComboBox/下拉箭头.svg);\n"
"    margin-right: 8px;\n"
"    margin-top: 15px;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    outline: none;\n"
"    color: #cccccc;\n"
"    font: 12pt \"Microsoft Tahei\";\n"
"    background: #303338;\n"
"    padding: 12px 6px 12px 6px;\n"
"}")
        self.TargetComboBox.setObjectName("TargetComboBox")
        self.TargetComboBox.addItem("")
        self.TargetComboBox.addItem("")
        self.TargetComboBox.addItem("")
        self.TargetComboBox.addItem("")
        self.TargetComboBox.addItem("")
        self.TargetComboBox.addItem("")
        self.TargetComboBox.addItem("")
        self.TargetComboBox.addItem("")
        self.TargetComboBox.addItem("")
        self.LanguageLayout.addWidget(self.TargetComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LanguageLayout.addItem(spacerItem)
        self.InputLayout.addLayout(self.LanguageLayout)
        self.InputTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.InputTextEdit.setMinimumSize(QtCore.QSize(360, 320))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(16)
        self.InputTextEdit.setFont(font)
        self.InputTextEdit.setToolTip("")
        self.InputTextEdit.setStyleSheet("QTextEdit {\n"
"    border: none;\n"
"    background-color: #27292F;\n"
"    font-family: \'Microsoft Yahei\';\n"
"    font-size: 16pt;\n"
"    color: white;\n"
"}")
        self.InputTextEdit.setObjectName("InputTextEdit")
        self.InputLayout.addWidget(self.InputTextEdit)
        self.TranslateLayout = QtWidgets.QHBoxLayout()
        self.TranslateLayout.setObjectName("TranslateLayout")
        self.UploadFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.UploadFileButton.setStyleSheet("QPushButton {\n"
"    height: 40px;\n"
"    width: 40px;\n"
"    border: none;\n"
"    border-image: url(:/UploadButton/上传文件.svg);\n"
"    margin-left: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/UploadButton/上传文件-hover.svg);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(:/UploadButton/上传文件-pressed.svg);\n"
"}\n"
"\n"
"QToolTip{\n"
"    background-color: #36393E;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    font: 8pt \"Microsoft Yahei\";\n"
"    color: #A7ABBD;\n"
"\n"
"}")
        self.UploadFileButton.setText("")
        self.UploadFileButton.setObjectName("UploadFileButton")
        self.TranslateLayout.addWidget(self.UploadFileButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TranslateLayout.addItem(spacerItem1)
        self.ClearButton = QtWidgets.QPushButton(self.centralwidget)
        self.ClearButton.setStyleSheet("QPushButton{\n"
"    height: 40px;\n"
"    width: 90px;\n"
"    font: 10pt \"Microsoft Yahei\";\n"
"    color: #969799;\n"
"    background-color: transparent;\n"
"    border: 1px solid #969799;\n"
"    border-radius: 12px;\n"
"\n"
"    margin-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(59, 61, 67);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(86, 85, 88);\n"
"}")
        self.ClearButton.setObjectName("ClearButton")
        self.TranslateLayout.addWidget(self.ClearButton)
        self.TranslateButton = QtWidgets.QPushButton(self.centralwidget)
        self.TranslateButton.setStyleSheet("QPushButton{\n"
"    height: 40px;\n"
"    width: 90px;\n"
"    font: 10pt \"Microsoft Yahei\";\n"
"    color: white;\n"
"    background-color: #FF584D;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"\n"
"    margin-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 52, 55);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(239, 95, 97)\n"
"}")
        self.TranslateButton.setObjectName("TranslateButton")
        self.TranslateLayout.addWidget(self.TranslateButton)
        self.InputLayout.addLayout(self.TranslateLayout)
        self.MainLayout.addLayout(self.InputLayout)
        self.PartingWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PartingWidget.sizePolicy().hasHeightForWidth())
        self.PartingWidget.setSizePolicy(sizePolicy)
        self.PartingWidget.setMinimumSize(QtCore.QSize(20, 0))
        self.PartingWidget.setMaximumSize(QtCore.QSize(20, 16777215))
        self.PartingWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PartingWidget.setObjectName("PartingWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.PartingWidget)
        self.verticalLayout.setContentsMargins(8, -1, 8, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PartingFrame = QtWidgets.QFrame(self.PartingWidget)
        self.PartingFrame.setStyleSheet("QFrame {\n"
"    border: none;\n"
"    border-right: 2px dashed #3B3C40;\n"
"    background: none;\n"
"}")
        self.PartingFrame.setFrameShape(QtWidgets.QFrame.VLine)
        self.PartingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PartingFrame.setObjectName("PartingFrame")
        self.verticalLayout.addWidget(self.PartingFrame)
        self.MainLayout.addWidget(self.PartingWidget)
        self.OutputLayout = QtWidgets.QVBoxLayout()
        self.OutputLayout.setObjectName("OutputLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 51))
        self.widget.setSizeIncrement(QtCore.QSize(0, 51))
        self.widget.setStyleSheet("QWidget{\n"
"    margin-bottom: 20px;\n"
"}")
        self.widget.setObjectName("widget")
        self.OutputLayout.addWidget(self.widget)
        self.OutputTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.OutputTextBrowser.setMinimumSize(QtCore.QSize(360, 320))
        self.OutputTextBrowser.setStyleSheet("QTextEdit {\n"
"    border: none;\n"
"    background-color: #27292F;\n"
"    font-family: \'Microsoft Yahei\';\n"
"    font-size: 16pt;\n"
"    color: white;\n"
"}")
        self.OutputTextBrowser.setObjectName("OutputTextBrowser")
        self.OutputLayout.addWidget(self.OutputTextBrowser)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CopyButton = QtWidgets.QPushButton(self.centralwidget)
        self.CopyButton.setStyleSheet("QPushButton {\n"
"    height: 40px;\n"
"    width: 40px;\n"
"    border: none;\n"
"    border-image: url(:/CopyButton/复制.svg);\n"
"    margin-left: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/CopyButton/复制-hover.svg);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(:/CopyButton/复制-pressed.svg);\n"
"}\n"
"\n"
"QToolTip{\n"
"    background-color: #36393E;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    font: 8pt \"Microsoft Yahei\";\n"
"    color: #A7ABBD;\n"
"\n"
"}")
        self.CopyButton.setText("")
        self.CopyButton.setObjectName("CopyButton")
        self.horizontalLayout_2.addWidget(self.CopyButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.OutputLayout.addLayout(self.horizontalLayout_2)
        self.MainLayout.addLayout(self.OutputLayout)
        self.verticalLayout_4.addLayout(self.MainLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.SourceComboBox.setCurrentIndex(0)
        self.TargetComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SourceComboBox.setCurrentText(_translate("MainWindow", "自动检测"))
        self.SourceComboBox.setItemText(0, _translate("MainWindow", "自动检测"))
        self.SourceComboBox.setItemText(1, _translate("MainWindow", "中文"))
        self.SourceComboBox.setItemText(2, _translate("MainWindow", "英语"))
        self.SourceComboBox.setItemText(3, _translate("MainWindow", "日语"))
        self.SourceComboBox.setItemText(4, _translate("MainWindow", "法语"))
        self.SourceComboBox.setItemText(5, _translate("MainWindow", "德语"))
        self.SourceComboBox.setItemText(6, _translate("MainWindow", "意大利语"))
        self.SourceComboBox.setItemText(7, _translate("MainWindow", "西班牙语"))
        self.SourceComboBox.setItemText(8, _translate("MainWindow", "葡萄牙语"))
        self.SourceComboBox.setItemText(9, _translate("MainWindow", "俄语"))
        self.SwapButton.setToolTip(_translate("MainWindow", "交换语言"))
        self.SwapButton.setText(_translate("MainWindow", "⇌"))
        self.TargetComboBox.setItemText(0, _translate("MainWindow", "中文"))
        self.TargetComboBox.setItemText(1, _translate("MainWindow", "英语"))
        self.TargetComboBox.setItemText(2, _translate("MainWindow", "日语"))
        self.TargetComboBox.setItemText(3, _translate("MainWindow", "法语"))
        self.TargetComboBox.setItemText(4, _translate("MainWindow", "德语"))
        self.TargetComboBox.setItemText(5, _translate("MainWindow", "意大利语"))
        self.TargetComboBox.setItemText(6, _translate("MainWindow", "西班牙语"))
        self.TargetComboBox.setItemText(7, _translate("MainWindow", "葡萄牙语"))
        self.TargetComboBox.setItemText(8, _translate("MainWindow", "俄语"))
        self.UploadFileButton.setToolTip(_translate("MainWindow", "文件翻译"))
        self.ClearButton.setText(_translate("MainWindow", "清空"))
        self.TranslateButton.setText(_translate("MainWindow", "翻译"))
        self.CopyButton.setToolTip(_translate("MainWindow", "复制"))
import pydeepl_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
